Numpy

In [ ]:
#Numpy is like list or tuples but stores the elements of the same datatype. This property makes it faster

In [3]:
import numpy as np

In [10]:
a = np.array([1,2,3,5],dtype='f')

In [5]:
b = np.array((1,5,6,7))

In [6]:
print(b)

[1 5 6 7]


In [7]:
type(a)

numpy.ndarray

In [8]:
type(b)

numpy.ndarray

In [11]:
a.dtype

dtype('float32')

In [12]:
b.dtype

dtype('int32')

In [13]:
#dtype stores the information of the datatype stored in the array.

In [14]:
a = np.array([[1,2,3],[3,4,5]])

In [15]:
a.ndim

2

In [16]:
# ndim is used for finding the dimensions of an array. The 1-D arrays should have same no of elements inside a 2-D array in order to get a 2-D array
# else it will be a 1-D array

In [17]:
a[1,2]

5

In [19]:
b = np.array([[[1,2,3],[4,2,1],[5,4,9]],[[8,7,5],[9,4,3],[2,1,0]]])

In [20]:
b.ndim

3

In [21]:
type(b)

numpy.ndarray

In [22]:
b.shape

(2, 3, 3)

In [25]:
b.shape[0] #used for finding no of 2-D arrays inside the 3-D array

2

In [26]:
b.shape[1] #used for finding no of 1-D arrays inside the 2-D array

3

In [27]:
b.shape[2] #used for finding no of elements inside the 1-D array

3

In [28]:
#if you define the numpy array as np.array(2) then the dimension will be 0. Therefore the elements must be enclosed within paranthesis in order to
# a non-zero dimensional array

In [29]:
b.size

18

In [30]:
b.nbytes

72

In [35]:
a = np.arange(100)

In [36]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [37]:
a = np.arange(10,20)

In [38]:
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [39]:
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [40]:
a = np.random.permutation(np.arange(10))
print(a)

[8 9 4 7 1 3 6 5 0 2]


In [43]:
np.random.randint(10,30)

25

In [44]:
c = np.random.rand(2,3)

In [45]:
c

array([[0.72092275, 0.41167357, 0.65867203],
       [0.36059043, 0.97631417, 0.79206603]])

In [46]:
c.ndim

2

In [47]:
c = np.random.rand(1,2,3,4)
c

array([[[[0.17879979, 0.40919085, 0.9023509 , 0.55436348],
         [0.30892669, 0.41679783, 0.59828805, 0.5589763 ],
         [0.97118404, 0.20274861, 0.70662685, 0.23651793]],

        [[0.98206026, 0.7080113 , 0.89509871, 0.14844107],
         [0.23265518, 0.15089049, 0.83219168, 0.03912325],
         [0.27639652, 0.25716796, 0.07718639, 0.80049748]]]])

In [48]:
d = np.arange(100).reshape(25,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [49]:
# Slicing
# A[start:stop:step]

In [50]:
# When you assign a slice to a variable, the memory is not copied rather the same memory location is accessed

In [51]:
a = np.arange(100)
b = a[3:10]
print(b)

[3 4 5 6 7 8 9]


In [52]:
b[0] = 20
print(b)
print(a)

[20  4  5  6  7  8  9]
[ 0  1  2 20  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [53]:
# but if you use b = a[3:0].copy() then the memory location is copied and any changes on b will not reflect to a

In [54]:
a[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [55]:
a[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4, 20,  2,  1,  0])

In [59]:
idx = np.argwhere(a==20)[0][0]
idx

3

In [60]:
a[3] = idx
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [85]:
a = np.round(10*np.random.rand(5,4))
a

array([[10.,  2.,  7.,  4.],
       [ 7.,  5., 10.,  6.],
       [ 9., 10., 10.,  1.],
       [ 1.,  4.,  9.,  7.],
       [ 6.,  1.,  3.,  6.]])

In [66]:
#Whole row can be accessed by a[row,:]

In [67]:
a[1,:]

array([10.,  7.,  9., 10.])

In [68]:
#Whole column can be accessed by a[:,col]

In [70]:
a[:,2]

array([4., 9., 6., 2., 4.])

In [71]:
a[1:3,0:2]

array([[10.,  7.],
       [ 6.,  3.]])

In [72]:
#transpose of matrix a.T

In [73]:
a.T

array([[ 0., 10.,  6.,  1.,  8.],
       [ 7.,  7.,  3.,  9.,  3.],
       [ 4.,  9.,  6.,  2.,  4.],
       [ 5., 10.,  7.,  9.,  3.]])

In [74]:
import numpy.linalg as la

In [75]:
la.inv(np.random.rand(3,3))

array([[ 1.72659851,  0.10458729, -1.7427105 ],
       [ 1.28438367, -1.84588839,  0.22830367],
       [-1.68553894,  1.82033167,  1.47939129]])

In [86]:
a.sort(axis=0) #sorting across columns

In [87]:
a

array([[ 1.,  1.,  3.,  1.],
       [ 6.,  2.,  7.,  4.],
       [ 7.,  4.,  9.,  6.],
       [ 9.,  5., 10.,  6.],
       [10., 10., 10.,  7.]])

In [88]:
a.sort(axis=1) #sorting across rows

In [89]:
a

array([[ 1.,  1.,  1.,  3.],
       [ 2.,  4.,  6.,  7.],
       [ 4.,  6.,  7.,  9.],
       [ 5.,  6.,  9., 10.],
       [ 7., 10., 10., 10.]])

In [90]:
a = np.arange(100)
b = a[[3,6,7]]
b

array([3, 6, 7])

In [91]:
#here if you try to make any changes to b it doesn't reflect to a

In [92]:
b[0] = -2

In [93]:
b

array([-2,  6,  7])

In [94]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [95]:
b = a[(a>30) & (a<40)]

In [96]:
b

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [97]:
# & is used for arrays while and is used for single objects. similarly (|,or) ,(~,not)

In [98]:
# broadcasting

In [99]:
b = b+5
b

array([36, 37, 38, 39, 40, 41, 42, 43, 44])

In [100]:
# You can also broadcast a row or column into a matrix. 

In [101]:
# Universal functions: These functions are very fast. it should be used instead of for loops. it is used for vectorised implementation.
# e.g: np.hstack (concatenates two matrices horizontally) , np.vstack (concatenates vertically) , np.sort

In [114]:
a = np.round(10*np.random.rand(2,3))
a

array([[6., 6., 3.],
       [6., 5., 8.]])

In [115]:
a+3

array([[ 9.,  9.,  6.],
       [ 9.,  8., 11.]])

In [121]:
a + (np.arange(2).reshape(2,1))

array([[6., 6., 3.],
       [7., 6., 9.]])

In [122]:
b = np.round(10*np.random.rand(2,2))

In [119]:
b

array([[ 3.,  6.],
       [10.,  3.]])

In [123]:
c = np.hstack((a,b))
c

array([[6., 6., 3., 4., 0.],
       [6., 5., 8., 6., 1.]])

In [124]:
a = np.random.permutation(np.arange(10))
a

array([1, 7, 5, 2, 6, 4, 0, 9, 8, 3])

In [128]:
a.sort()

In [129]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
a = a[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [132]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
a = np.array(["hello","23Jacks", "Zachary" , "&hello"])
a.sort()

In [134]:
a

array(['&hello', '23Jacks', 'Zachary', 'hello'], dtype='<U7')

In [136]:
b = np.random.rand(1000000)
%timeit sum(b)
%timeit np.sum(b)

200 ms ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.45 ms ± 62.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
